volumes:
  db:
version: '3'
name: restoration-project
services:
  db:
    container_name: restoration-project-db
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - db:/var/lib/postgresql/data
