name: Deployment

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npx prisma generate
      - run: cat .env.example > .env
      - run: npm run build
      - run: npm run test

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: witnessesoftherestoration.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sh deploy.sh